baseURL = "https://enjikaka.github.io/btc-hugo"
languageCode = "sv"
languageName = "svenska"
defaultContentLanguage = "sv"
title = "ByggTeknikCentrum"
theme = "btc-hugo-theme"
keywords = "ritningar, hus, fritidshus, garage, byggritningar, bygglovsritningar, ByggTeknikCentrum, konstruktionsritningar, energiberäkning, kontrollansvarig, konstruktionsberäkningar"
sectionPagesMenu = "main"
enableGitInfo = true

[permalinks]
  sida = "/sida/:title"
  ritningspaket = "/ritningspaket/:title"
